# ./docker-compose.yml
version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: banco_postgres
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/DataBase.sql:/docker-entrypoint-initdb.d/DataBase.sql

volumes:
  postgres_data:
